lowercaseOutputName: true
lowercaseOutputLabelNames: true

rules:
  - pattern: "kafka.connect<type=connect-worker-metrics><>([^:]+)"
    name: kafka_connect_worker_$1

  - pattern: "kafka.connect<type=connector-metrics, connector=(.+)><>([^:]+)"
    name: kafka_connect_connector_$2
    labels:
      connector: "$1"

  - pattern: "kafka.connect<type=connector-task-metrics, connector=(.+), task=(\\d+)><>([^:]+)"
    name: kafka_connect_task_$3
    labels:
      connector: "$1"
      task: "$2"

  - pattern: "kafka.connect<type=task-error-metrics, connector=(.+), task=(\\d+)><>([^:]+)"
    name: kafka_connect_task_error_$3
    labels:
      connector: "$1"
      task: "$2"

  - pattern: "debezium.postgres<type=connector-metrics, context=(.+), server=(.+)><>([^:]+)"
    name: debezium_postgres_$3
    labels:
      context: "$1"
      server: "$2"

  - pattern: "java.lang<type=Memory><HeapMemoryUsage>(\\w+)"
    name: jvm_memory_heap_$1

  - pattern: "java.lang<type=GarbageCollector, name=(.+)><>(\\w+)"
    name: jvm_gc_$2
    labels:
      gc: "$1"
