package com.keene.streaming.repository;

import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceContext;
import jakarta.persistence.TypedQuery;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.lang.NonNull;
import org.springframework.stereotype.Repository;

/**
 * Custom implementation of GeoClientRepository.
 * This class provides custom implementations for methods that cannot be
 * automatically generated by Spring Data JPA query derivation.
 * 
 * Note: Spring Data JPA automatically implements most methods from JpaRepository
 * (save, deleteById, findAll, findById, etc.) and query methods following naming
 * conventions (findByGuid, existsByGuid, etc.).
 */
@Repository
public class GeoClientRepositoryImpl implements GeoClientRepositoryCustom {

    private static final Logger logger = LoggerFactory.getLogger(GeoClientRepositoryImpl.class);

    @PersistenceContext
    private EntityManager entityManager;

    public void setEntityManager(EntityManager entityManager) {
        this.entityManager = entityManager;
    }

    /**
     * Count all geo clients in the database.
     * 
     * @return the total count of geo clients
     */
    @Override
    @NonNull
    public Long countGeoClients() {
        logger.debug("Counting all geo clients");
        
        String jpql = "SELECT COUNT(g) FROM GeoClient g";
        TypedQuery<Long> query = entityManager.createQuery(jpql, Long.class);
        try{ 
            Long count = query.getSingleResult();
            logger.debug("Found {} geo clients", count);
            if (count == null) {
                return 0L;
            } else {
                return count;
            }
        } finally {
            //
        }
    }
}

