package com.keene.streaming.repository;

import java.util.List;

import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceContext;
import jakarta.persistence.TypedQuery;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.lang.NonNull;
import org.springframework.stereotype.Repository;

import com.keene.streaming.core.models.Scalar;

/**
 * Custom implementation of ScalarRepository.
 * Provides custom implementations for methods that cannot be
 * automatically generated by Spring Data JPA query derivation.
 */
@Repository
public class ScalarRepositoryImpl implements ScalarRepositoryCustom {

    private static final Logger logger = LoggerFactory.getLogger(ScalarRepositoryImpl.class);

    @PersistenceContext
    private EntityManager entityManager;

    @Override
    @NonNull
    public Long countScalars() {
        logger.debug("Counting all scalars");
        String jpql = "SELECT COUNT(s) FROM Scalar s";
        TypedQuery<Long> query = entityManager.createQuery(jpql, Long.class);
        Long count = query.getSingleResult();
        logger.debug("Found {} scalars", count);
        return count != null ? count : 0L;
    }

    @Override
    @NonNull
    public List<Scalar> findScalars(int offset, int count) {
        logger.debug("Finding scalars with offset {} and count {}", offset, count);
        String jpql = "SELECT s FROM Scalar s ORDER BY s.id ASC";
        TypedQuery<Scalar> query = entityManager.createQuery(jpql, Scalar.class);
        query.setFirstResult(offset);
        query.setMaxResults(count);
        return query.getResultList();
    }
}
