package com.keene.streaming.repository;

import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceContext;
import jakarta.persistence.TypedQuery;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.lang.NonNull;
import org.springframework.stereotype.Repository;

/**
 * Custom implementation of ScalarRepository.
 * Provides custom implementations for methods that cannot be
 * automatically generated by Spring Data JPA query derivation.
 */
@Repository
public class ScalarRepositoryImpl implements ScalarRepositoryCustom {

    private static final Logger logger = LoggerFactory.getLogger(ScalarRepositoryImpl.class);

    @PersistenceContext
    private EntityManager entityManager;

    @Override
    @NonNull
    public Long countScalars() {
        logger.debug("Counting all scalars");
        String jpql = "SELECT COUNT(s) FROM Scalar s";
        TypedQuery<Long> query = entityManager.createQuery(jpql, Long.class);
        Long count = query.getSingleResult();
        logger.debug("Found {} scalars", count);
        return count != null ? count : 0L;
    }
}
