package com.keene.streaming.repository;

import java.util.List;

import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceContext;
import jakarta.persistence.TypedQuery;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.lang.NonNull;
import org.springframework.stereotype.Repository;

import com.keene.streaming.core.models.Wide;

/**
 * Custom implementation of WideRepository.
 * Provides custom implementations for methods that cannot be
 * automatically generated by Spring Data JPA query derivation.
 */
@Repository
public class WideRepositoryImpl implements WideRepositoryCustom {

    private static final Logger logger = LoggerFactory.getLogger(WideRepositoryImpl.class);

    @PersistenceContext
    private EntityManager entityManager;

    @Override
    @NonNull
    public Long countWides() {
        logger.debug("Counting all wide rows");
        String jpql = "SELECT COUNT(w) FROM Wide w";
        TypedQuery<Long> query = entityManager.createQuery(jpql, Long.class);
        Long count = query.getSingleResult();
        logger.debug("Found {} wide rows", count);
        return count != null ? count : 0L;
    }

    @Override
    @NonNull
    public List<Wide> findWides(int offset, int count) {
        logger.debug("Finding wide rows with offset {} and count {}", offset, count);
        String jpql = "SELECT w FROM Wide w ORDER BY w.id ASC";
        TypedQuery<Wide> query = entityManager.createQuery(jpql, Wide.class);
        query.setFirstResult(offset);
        query.setMaxResults(count);
        return query.getResultList();
    }
}
